# Generated by Django 4.2.19 on 2025-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_options_alter_category_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
