# Generated by Django 4.2.19 on 2025-03-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_likes_alter_like_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='test_field',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
