# Generated by Django 4.2.19 on 2025-03-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_baker_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baker',
            name='test_field',
        ),
    ]
