# Generated by Django 4.2.19 on 2025-03-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_baker_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/static/assets/images'),
        ),
    ]
