# Generated by Django 4.2.19 on 2025-03-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baker',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='recipes/static/assets/images/profile_pics'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/static/assets/images/recipe_images'),
        ),
    ]
