# Generated by Django 4.2.19 on 2025-03-12 11:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_baker_profile_pic_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baker',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
