# Generated by Django 4.2.19 on 2025-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(default='', verbose_name='blurb'),
        ),
    ]
