# Generated by Django 4.2.19 on 2025-03-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='baker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.baker'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe'),
        ),
    ]
